; ============================================================
;  RhythmClass firmware
; ============================================================

[platformio]
default_envs = d1mini

; ---- D1 Mini (production) -----------------------------------
[env:d1mini]
platform  = espressif8266
board     = d1_mini
framework = arduino
build_flags =
    -std=gnu++17
lib_deps =
    fastled/FastLED
    rfetick/MPU6050_light
build_src_filter =
    +<*.h>
    +<main_${PIOENV}.cpp>
test_ignore = *
extra_scripts = pre:utils.py  ;injects version into main
monitor_speed = 115200

; ---- Native unit tests --------------------------------------
[env:test_native]
platform       = native
build_type     = test
build_flags    =
    -std=gnu++2a
    -D IS_TESTING
test_framework = googletest
lib_deps       =
    googletest
build_src_filter =
    +<main_${PIOENV}.cpp>
test_build_src = yes
